### ISSUE TITLE
Feature Request: Create an independent css snippet 

### ISSUE THREAD

**Issue by beviz** [caro401/royal-velvet#15]
Hi team, thanks for your great job. After trying almost the top 100 themes, I believe this theme is the most beautiful one(not one of).

But you know, there is another theme called Minimal. It's the most popular one and it supports a lot of features. So I want to have both its features and your styles.

I think there is only one way to do that, which is to use the Minimal theme and royal-velvet CSS snippet, or the opposite. 

Therefore:

**Feature Requested**
Could you please provide a CSS file that is compatible(overwrite) with the Minimal theme? 

It will save my life because I switched too many times between these two themes... I will appreciate it.

**Comment by LEFD** [comment]
I'm gonna close this issue, because since Obsidian released v1.0.0, the UI looks pretty much like the Minimal theme.
