### ISSUE TITLE
[BUG] Characters disappearing in headings

### ISSUE THREAD

**Issue by Toiler-zz** [caro401/royal-velvet#17]
**Describe the Bug**
When in editing mode, headers (of any size) seem to make some words disapear in editing mode (although not in preview mode). Adding special symbols seem to remove the issue, like seen in the picture below (Work'sss)

**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/2026842/176984642-5f7aaa6f-1d9f-416e-a414-0682161360a2.png)

![image](https://user-images.githubusercontent.com/2026842/176984869-0c940eaf-7775-41ac-95a4-49d1d8ace3d3.png)

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Make a header
2. Type a word of any length, bugs out some words, usually longer ones
3. For example, when i Write Sci-Fi, the "Fi" part becomes transparent, but the Sci remains visable

**In which mode does the bug occur?**
- [x] Editing mode only

**Which editor are you using?**
- [x] Legacy Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**End Note**
The vault I'm testing this in has very few plugins that would affect this as far as I'm aware (plugins like dataview, or non-css related). I only have 1 snippet active, and it just hides the metadata at the top of the note

```
.frontmatter-container {
    display: none;
}
```

**Comment by caro401** [comment]
Thanks for the detailed bug report, I'll take a look as soon as I can
