### ISSUE TITLE
[BUG] --code-size: 100%; breaks some plugins

### ISSUE THREAD

**Issue by KiwiFlavorBepis** [caro401/royal-velvet#44]
**Describe the Bug**
The `--code-size` CSS variable uses a percentage:
- In the default Obsidian theme, the `--code-size` variable is set to `--font-smaller` which has a value of `0.875em`.
- Plugins expect the `--code-size` variable to be in terms of `em`.
- In Royal Velvet, the `--code-size` variable is set to `100%`.

**Potential Fix**
Replace `--code-size: 100%;` with `--code-size: 1em;`. The effect is the same.

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by LEFD** [comment]
thanks for the bug report! i'll look into it, as soon as I can.

**Comment by KiwiFlavorBepis** [comment]
Just made a pull request #45 with the change. Its only 1 line.
