### ISSUE TITLE
Heading colour does not apply when the heading has spelling errors 

### ISSUE THREAD

**Issue by adronysko** [caro401/royal-velvet#48]
![Screenshot from 2024-11-21 20-11-13](https://github.com/user-attachments/assets/28c2b648-9fcf-4083-b21a-ec35284ac956)

Hi there. The issue is evident from the title: The text colour reverts to the program default (ie: black in light mode) as soon as the spellcheck red underline appears. This applies to all headings H1 through H6. I think this is a new issue as I don't recall it happening before, but can't say for sure.

**Comment by LEFD** [comment]
Hi! Thanks for bringing this to my attention! I noticed the same thing and wasn't sure if this was happening before as well. New Obsidian release must be causing this.
