### ISSUE TITLE
[BUG] margin of folders is too big when using Obsidian Icon Folder plugin

### ISSUE THREAD

**Issue by LEFD** [caro401/royal-velvet#6]
**Describe the Bug**
When using the plugin "Obsidian Icon Folder", folders with an emoji as an icon have a too big margin compared to other folders. See screenshot below.

![Screenshot 2022-03-20 203604](https://user-images.githubusercontent.com/78652025/159179844-64dd3f21-ae35-4545-9261-b9b52a97d6b0.png)

removing the following lines fixes this issue:
``` css
img,
.markdown-source-view.mod-cm6 .cm-content > img {
  margin: 1ch !important;
}
```

**To Reproduce**
1. install "Obsidian Icon Folder" plugin 
2. set an emoji as a folder or file icon (right click on folder -> change icon -> type emoji in text field -> select emoji)

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [x] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by caro401** [comment]
Thank you for your really great bug reports!
